import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { far } from '@fortawesome/free-regular-svg-icons';
import { fas } from '@fortawesome/free-solid-svg-icons';

const root = path.resolve(import.meta.dirname, '..');
const assetsDirectory = path.join(root, 'assets');
const iconDefinitionsPath = path.join(root, 'scripts', 'data', 'icon-definitions.js');

const imageJobs = [
  ['branch-gavrilova-960.webp', 'branch-gavrilova', [360, 720]],
  ['branch-lermontova-800.webp', 'branch-lermontova', [480]],
  ['card-checkup-1672.webp', 'card-checkup', [480, 960]],
  ['card-child-1672.webp', 'card-child', [480, 960]],
  ['card-corporate-1672.webp', 'card-corporate', [480, 960]],
  ['card-cosmetology-1672.webp', 'card-cosmetology', [480, 960]],
  ['card-doctor-1672.webp', 'card-doctor', [480, 960]],
  ['clinic-team-gavrilova-1280.webp', 'clinic-team-gavrilova', [480, 960]],
  ['doctor-myasnikov-1200.webp', 'doctor-myasnikov', [320, 640, 960]],
  ['doctor-botova-960.webp', 'doctor-botova', [320, 640]],
  ['doctor-fedash-960.webp', 'doctor-fedash', [320, 640]],
  ['doctor-nilova-960.webp', 'doctor-nilova', [320, 640]],
  ['doctor-piksaeva-960.webp', 'doctor-piksaeva', [320, 640]],
  ['doctor-stepanova-960.webp', 'doctor-stepanova', [320, 640]],
  ['doctor-sukhareva-634.webp', 'doctor-sukhareva', [320]],
  ['doctor-myasnikova-960.webp', 'doctor-myasnikova', [320, 640]],
  ['doctor-yuryeva-960.webp', 'doctor-yuryeva', [320, 640]],
  ['hero-clinic-1920.webp', 'hero-clinic', [480, 960]],
  ['infusion-room-1586.webp', 'infusion-room', [480, 960]],
  ['reception-hero-1672.webp', 'reception-hero', [480, 960]],
  ['ultrasound-1500.webp', 'ultrasound', [480, 960]]
];

const mimeByExtension = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp'
};

function getIconIndex(collection) {
  const icons = new Map();

  Object.values(collection).forEach((definition) => {
    if (definition?.iconName && definition?.icon && !icons.has(definition.iconName)) {
      icons.set(definition.iconName, definition);
    }
  });

  return icons;
}

function findRequestedIcons() {
  const sourceFiles = [
    ...fs.readdirSync(root)
      .filter((file) => file.endsWith('.html'))
      .map((file) => path.join(root, file)),
    ...fs.readdirSync(path.join(root, 'scripts'), { recursive: true, withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.endsWith('.js'))
      .map((entry) => path.join(entry.parentPath, entry.name))
  ];
  const requested = new Map();
  const iconPattern = /fa-(solid|regular)[^"']*?fa-([a-z0-9-]+)/g;

  sourceFiles.forEach((file) => {
    const source = fs.readFileSync(file, 'utf8');
    for (const match of source.matchAll(iconPattern)) {
      requested.set(`${match[1]}-${match[2]}`, {
        style: match[1],
        name: match[2]
      });
    }
  });

  return [...requested.values()].sort((a, b) => (
    `${a.style}-${a.name}`.localeCompare(`${b.style}-${b.name}`)
  ));
}

function buildIconDefinitions() {
  const solidIcons = getIconIndex(fas);
  const regularIcons = getIconIndex(far);
  const definitions = Object.fromEntries(findRequestedIcons().map(({ style, name }) => {
    const definition = (style === 'regular' ? regularIcons : solidIcons).get(name);
    if (!definition) throw new Error(`Font Awesome icon not found: ${style} ${name}`);

    const [width, height, , , pathData] = definition.icon;
    return [`fa-${style}-${name}`, {
      viewBox: `0 0 ${width} ${height}`,
      paths: Array.isArray(pathData) ? pathData : [pathData]
    }];
  }));

  const moduleSource = `// Generated by tools/build-assets.mjs. Do not edit manually.\nglobalThis.DOCTOR38_ICON_DEFINITIONS = Object.freeze(${JSON.stringify(definitions)});\n`;
  fs.writeFileSync(iconDefinitionsPath, moduleSource);
  console.log(`Created scripts/data/icon-definitions.js with ${Object.keys(definitions).length} icons`);
}

async function encodeResponsiveImages() {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage();

  try {
    for (const [fileName, stem, widths] of imageJobs) {
      const inputPath = path.join(assetsDirectory, fileName);
      const extension = path.extname(fileName).toLowerCase();
      const data = fs.readFileSync(inputPath).toString('base64');
      const mime = mimeByExtension[extension];
      if (!mime) throw new Error(`Unsupported image format: ${fileName}`);

      const variants = await page.evaluate(async ({ data, mime, widths }) => {
        const source = await createImageBitmap(await (await fetch(`data:${mime};base64,${data}`)).blob());
        const results = [];

        for (const width of widths) {
          const canvas = document.createElement('canvas');
          canvas.width = width;
          canvas.height = Math.round(source.height * width / source.width);
          canvas.getContext('2d').drawImage(source, 0, 0, canvas.width, canvas.height);
          const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/webp', 0.84));
          const encoded = await new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result.split(',')[1]);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
          });
          results.push({ width, encoded });
        }

        source.close();
        return results;
      }, { data, mime, widths });

      variants.forEach(({ width, encoded }) => {
        const outputPath = path.join(assetsDirectory, `${stem}-${width}.webp`);
        fs.writeFileSync(outputPath, Buffer.from(encoded, 'base64'));
      });
      console.log(`Created ${variants.length} responsive variants for ${fileName}`);
    }
  } finally {
    await browser.close();
  }
}

await encodeResponsiveImages();
buildIconDefinitions();
